name: Bug report
description: Create a report to help us improve
labels: ":bug:bug"

body:
  - type: markdown
    id: description
    attributes:
      value: |
        ## Before posting a feature request
        Search existing [GitHub issues](https://github.com/MadAnalysis/madanalysis5/issues) or [Launchpad](https://answers.launchpad.net/madanalysis5) to make sure the issue does not already exist.

        For general technical details check out our [documentation](http://arxiv.org/abs/1206.1599), [tutorials](https://madanalysis.irmp.ucl.ac.be/wiki/tutorials) and reference cards provided under `doc` folder.
        
        **Note:** Latest release of MadAnalysis 5 can be found at [this link](https://github.com/MadAnalysis/madanalysis5/releases).
        
        * **Please use [Markdown syntax](https://docs.github.com/en/get-started/writing-on-github/getting-started-with-writing-and-formatting-on-github/basic-writing-and-formatting-syntax).**
  - type: textarea
    id: system
    attributes:
      label: System Settings
      description: |
        Please provide
        - OS: [e.g. macOS v12.1]
        - Python version (print the output of `$ python --version`)
        - gcc/c++ version (print the output of `$ g++ --version` or `$ gcc --version`)
        - MadAnalysis 5 version (print the output of `$ ./bin/ma5 --version` or if you are working on a branch please report the name of the branch and last commit ID. The abbreviated commit ID can be found via `git log -n1 --format="%h"` command. To retreive the branch name please use `git rev-parse --abbrev-ref HEAD` command.)
        - If applicable, versions for other third party software i.e. Fastjet, Delphes, pyhf etc.
    validations:
      required: true
  - type: textarea
    id: details
    attributes:
      label: Describe the bug
      description: |
        A clear and concise description of what the bug is.
    validations:
      required: true
  - type: textarea
    id: reproduce
    attributes:
      label: To Reproduce
      description: |
        Steps to reproduce the behaviour:
          - If in normal mode, a list of MadAnalysis 5 commands.
          - If in expert mode, **minimal** code example.
          - If the bug occurs in a specific event file, please attach the event file by constraining it to **only** 10 events.
    validations:
      required: true
  - type: textarea
    id: expectation
    attributes:
      label: Expected behaviour
      description: |
        A clear and concise description of what you expected to happen.
  - type: textarea
    id: log
    attributes:
      label: Log files
      description: |
        If applicable, add log files or error messages to help explain your problem.

        Note: When run in debug mode, MadAnalysis 5 can give much more information about the problem. 
        
        - Debug mode can be activated via `$ ./bin/ma5 -d`
  - type: textarea
    id: info
    attributes:
      label: Additional information
      description: |
        Add any other context about the problem here.

