################################################################################
#  
#  Copyright (C) 2012-2026 Jack Araz, Eric Conte & Benjamin Fuks
#  The MadAnalysis development team, email: <ma5team@iphc.cnrs.fr>
#  
#  This file is part of MadAnalysis 5.
#  Official website: <https://github.com/MadAnalysis/madanalysis5>
#  
#  MadAnalysis 5 is free software: you can redistribute it and/or modify
#  it under the terms of the GNU General Public License as published by
#  the Free Software Foundation, either version 3 of the License, or
#  (at your option) any later version.
#  
#  MadAnalysis 5 is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
#  GNU General Public License for more details.
#  
#  You should have received a copy of the GNU General Public License
#  along with MadAnalysis 5. If not, see <http://www.gnu.org/licenses/>
#  
################################################################################


"""Expert mode of MadAnalysis 5 (``./bin/ma5 -e``).

The expert mode creates a standalone SampleAnalyzer working directory containing an
empty C++ analysis class (generated by ``newAnalyzer.py``) that the user completes by
hand, compiles with ``make`` and runs on a list of event files. When an SFS card is
provided, the SFS smearing/tagging modules are generated and included as well.
"""

from __future__ import absolute_import
from __future__ import annotations
from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from madanalysis.core.main import Main
from madanalysis.IOinterface.folder_writer import FolderWriter
from madanalysis.IOinterface.job_writer import JobWriter
import logging
import glob
import os
import sys
import shutil
from six.moves import input

class ExpertMode:
    """Creator of an expert-mode working directory.

    Attributes:
        main (``Main``): session state.
        path (``str``): absolute path of the working directory (set by
            :meth:`CreateDirectory`).
        forbiddenpaths (``list[str]``): MadAnalysis 5 folders that cannot be used as
            working directory.
    """

    def __init__(self,main: Main) -> None:
        """Initialise the expert mode.

        Args:
            main (``Main``): session state.
        """
        self.main=main
        self.path=""
        self.forbiddenpaths=[]
        self.forbiddenpaths.append(os.path.normpath(self.main.archi_info.ma5dir+'/lib'))
        self.forbiddenpaths.append(os.path.normpath(self.main.archi_info.ma5dir+'/bin'))
        self.forbiddenpaths.append(os.path.normpath(self.main.archi_info.ma5dir+'/madanalysis'))
        
    def CreateDirectory(self,name: str) -> bool:
        """Determine (and clean) the working directory.

        If ``name`` is empty, the user is asked for it interactively (spaces and dashes
        are replaced by underscores). Relative paths are resolved with respect to the
        current directory, except ``tools/PAD`` and ``tools/PADForMA5tune`` that are
        resolved with respect to the MadAnalysis 5 installation. If the directory
        already exists, the user is asked whether it can be removed.

        Args:
            name (``str``): name of the working directory (may be empty).

        Returns:
            ``bool``:
            ``True`` if the directory can be (re)created, ``False`` otherwise.
        """
        if name=="":
          logging.getLogger('MA5').debug("Debug mode: no directory name is specified.")
          logging.getLogger('MA5').info("\nWelcome to the expert mode of MadAnalysis")
          logging.getLogger('MA5').info("Please enter a folder name for creating an empty SampleAnalyzer job")
          answer=input("Answer: ")
          answer=answer.replace(' ','_')
          name  =answer.replace('-','_')
        else:
          logging.getLogger('MA5').debug("Debug mode: a directory name is specified.")

        # Getting the full path
        self.path = os.path.expanduser(name)
        if not self.path.startswith('/'):
            if name in ['tools/PAD', 'tools/PADForMA5tune']:
                self.path = self.main.archi_info.ma5dir+'/'+self.path
            else:
                self.path = self.main.currentdir+'/'+self.path
        self.path = os.path.normpath(self.path)
        logging.getLogger('MA5').debug("Full path of the working directory: "+self.path)

        # Checking folder
        logging.getLogger('MA5').debug("Check that the path is not forbidden...")
        if self.path in self.forbiddenpaths:
            # FIXME: 'answer' is only defined when the name was asked interactively; a NameError is raised
            # when a forbidden directory is given on the command line (use 'name' instead).
            logging.getLogger('MA5').error("the folder '"+answer+"' is a MadAnalysis folder. " + \
                         "You cannot overwrite it. Please choose another folder.")
            return False

        # Checking if the job folder exists, if not remove it
        if os.path.isdir(self.path):
            logging.getLogger('MA5').debug("Remove the previous folder?")
            question="A directory called '"+self.path+"' is already defined.\n"+\
                 "Would you like to remove it ? (Y/N)"
            test = FolderWriter.RemoveDirectory(self.path,question)
            if not test[0] or not test[1]:
                return False

        return True


    def Copy(self,name: str,config: str = '') -> bool:
        """Create the working directory and write the analysis skeleton.

        The directory structure and Makefiles are created with
        :class:`~madanalysis.IOinterface.job_writer.JobWriter`, a blank analysis class
        called ``name`` is generated with ``newAnalyzer.py``, and the main program
        ``Build/Main/main.cpp`` is written (output file ``user.saf``). If an SFS card is
        given, it is loaded through a nested interpreter, the SFS C++ modules are
        generated and included in ``analysisList.h``.

        Args:
            name (``str``): name of the analysis class (asked interactively if empty).
            config (``str``, default ``''``): path to an SFS card (MadAnalysis 5 script).

        Returns:
            ``bool``:
            ``True`` on success, ``False`` otherwise.
        """
        if config!='':
            # Load the analysis card
            from madanalysis.core.script_stack       import ScriptStack
            from madanalysis.interpreter.interpreter import Interpreter
            ScriptStack.AddScript(config)
            self.main.script = True
            interpreter = Interpreter(self.main)
            interpreter.load(verbose=self.main.developer_mode)


        # Initializing the JobWriter
        jobber = JobWriter(self.main,self.path,False)

        # Writing process
        logging.getLogger('MA5').info("   Creating folder '"+self.path+"'...")
        if not jobber.Open():
            logging.getLogger('MA5').error("job submission aborted.")
            return False

        # Copying SampleAnalyzer
        logging.getLogger('MA5').info("   Copying required 'SampleAnalyzer' source files...")
        if not jobber.CopyLHEAnalysis():
            logging.getLogger('MA5').error("   job submission aborted.")
            return False

        # Write config file inputs
        if config!='':
            if not jobber.WriteSelectionHeader(self.main):
                return False
            os.remove(self.path+'/Build/SampleAnalyzer/User/Analyzer/user.h')
            if not jobber.WriteSelectionSource(self.main):
                return False
            os.remove(self.path+'/Build/SampleAnalyzer/User/Analyzer/user.cpp')
            os.remove(self.path+'/Build/SampleAnalyzer/User/Analyzer/analysisList.h')

        # Writing an empty analysis
        if name=="":
          logging.getLogger('MA5').info("Please enter a name for your analysis")
          title=input("Answer: ")
          if title=="":
              title="user"
          title=title.replace(' ', '_');
          name=title.replace('-', '_');
        logging.getLogger('MA5').info("   Writing an empty analysis...")
        import sys
        # NOTE: shell command built by string concatenation; paths containing spaces break it.
        os.system("cd "+self.path+"/Build/SampleAnalyzer; "+sys.executable+" newAnalyzer.py " + name + " 1")

        # Extracting analysis name
        # FIXME: the result of the os.system call above is not checked before opening analysisList.h.
        file = open(self.path+"/Build/SampleAnalyzer/User/Analyzer/analysisList.h")
        title=""
        for line in file:
            if "Add" not in line:
                continue
            words = line.split('"')
            if len(words)>=3:
                title=words[1]
                break
        file.close()

        # Writing a Makefile
        logging.getLogger('MA5').info("   Writing a 'Makefile'...")
        if not jobber.WriteMakefiles():
            logging.getLogger('MA5').error("job submission aborted.")
            return False

        # Writing Main
        if not jobber.CreateBldDir(analysisName=title,outputName="user.saf"):
            logging.getLogger('MA5').error("   job submission aborted.")
            return False

        # if fastsim functionalities are needed
        if config!='':
            with open(self.path+'/Build/SampleAnalyzer/User/Analyzer/analysisList.h','r') as f:
                header = f.readlines()
                to_include = [x for x in os.listdir(self.path + '/Build/SampleAnalyzer/User/Analyzer/') if
                              x in ['new_smearer_reco.h', 'new_tagger.h']]

            top_header    = header[:header.index('// -----------------------------------------------------------------------------\n')]
            bottom_header = header[header.index('// -----------------------------------------------------------------------------\n'):]
            for idx, inc in enumerate(to_include):
                if idx == 0:
                    top_header.append("/// SFS Headers\n")
                top_header.append('#include "'+inc+'"\n')
            open(self.path+'/Build/SampleAnalyzer/User/Analyzer/analysisList.h','w').writelines(top_header+bottom_header)

        return True


    def GiveAdvice(self) -> None:
        """Log the instructions to compile and run the expert-mode analysis."""
        logging.getLogger('MA5').info("\nGuidelines for writing an analysis in expert mode\n")
        logging.getLogger('MA5').info(" 1. Entering the directory '"+self.path+"/Build'\n")
        logging.getLogger('MA5').info(" 2. Setting the environment variables by loading setup.sh or setup.csh according to your SHELL\n")
        logging.getLogger('MA5').info(" 3. Entering the directory '"+self.path+"/Build/SampleAnalyzer/User/Analyzer'\n")
        # FIXME: the generated files are named '<analysis>.h/.cpp', not 'user.h/user.cpp'.
        logging.getLogger('MA5').info(" 4. Editing Analysis 'user.h' and 'user.cpp' files\n")
        logging.getLogger('MA5').info(" 5. Entering the directory '"+self.path+"/Build'\n")
        logging.getLogger('MA5').info(" 6. Compiling with the command 'make'\n")
        logging.getLogger('MA5').info(" 7. Writing a list of datasets\n")
        logging.getLogger('MA5').info(" 8. Launching SampleAnalyzer with the list of datasets\n")
