////////////////////////////////////////////////////////////////////////////////
//
//  Copyright (C) 2012-2023 Jack Araz, Eric Conte & Benjamin Fuks
//  The MadAnalysis development team, email: <ma5team@iphc.cnrs.fr>
//
//  This file is part of MadAnalysis 5.
//  Official website: <https://github.com/MadAnalysis/madanalysis5>
//
//  MadAnalysis 5 is free software: you can redistribute it and/or modify
//  it under the terms of the GNU General Public License as published by
//  the Free Software Foundation, either version 3 of the License, or
//  (at your option) any later version.
//
//  MadAnalysis 5 is distributed in the hope that it will be useful,
//  but WITHOUT ANY WARRANTY; without even the implied warranty of
//  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
//  GNU General Public License for more details.
//
//  You should have const Received a copy of the GNU General Public License
//  along with MadAnalysis 5. If not, see <http://www.gnu.org/licenses/>
//
////////////////////////////////////////////////////////////////////////////////

/**
 * @file SFSTaggerBase.h
 * @brief Base class of the Simplified Fast Simulation (SFS) taggers.
 */

#ifndef MADANALYSIS5_SFSTAGGERBASE_H
#define MADANALYSIS5_SFSTAGGERBASE_H

// SampleAnalyser headers
#include "SampleAnalyzer/Commons/DataFormat/EventFormat.h"

namespace MA5 {

    /** @brief Working point of a tagger (loose, medium or tight). */
    enum TaggerStatus {LOOSE, MID, TIGHT};

    /** @brief Options of the truth-level matching used by SFSTaggerBase. */
    struct SFSTaggerBaseOptions {
        /// @brief Tagging options
        ///
        /// @code btag_matching_deltaR : double @endcode
        /// matching deltaR is the upper threshold on the dR distance between a jet and B-hadron
        /// @code  btag_exclusive : bool @endcode
        /// The exclusive algorithm is designed to dynamically find the jet that best matches with a given B-hadron
        ///
        /// options starting with ctag and tautag are the ones corresponding to c-jet and tau-jet tagging
        ///
        /// @warning Old tagger did not have c-tagger. In order to match the results from the old
        /// tagger, adding @code enable_ctagging = false @endcode .This makes sure that the results
        /// do not change between versions. Additionally @code deltaR = 0.5 @endcode was the default
        /// value in old version that has been reinstated as well.
        ///
        /// @code taujtag_jetbased : bool@endcode
        /// States the nature of the tau tagging proecedure. If false, hadronic taus in the event history
        /// will be found and used as hadronic tau object. If True, this hadronic tau will be matched with
        /// a jet and the jet will be considered as a tau jet.
        ///
        /// @warning DR matching for tau tagging is only available with the jet-based method
        MAfloat32 btag_matching_deltaR = 0.5;
        MAbool btag_exclusive = true;
        MAbool enable_ctagging = false;
        MAfloat32 ctag_matching_deltaR = 0.5;
        MAbool ctag_exclusive = true;
        MAfloat32 tautag_matching_deltaR = 0.5;
        MAbool tautag_exclusive = true;
        MAbool tautag_jetbased = false;
    };

    /**
     * @brief Base class of the SFS b-, c-, tau- and object (mis)taggers.
     *
     * Truth-level b/c/tau tagging is based on the geometric matching of the jets with
     * B/C hadrons and hadronic taus (see SFSTaggerBaseOptions). Detector-level effects
     * are applied through the efficiency methods, which are overridden by the class
     * NewTagger generated by MadAnalysis 5 (new_tagger.h/cpp) from the `define tagger`
     * commands.
     *
     * Conventions of the efficiency methods: the returned value is compared with a
     * uniform random number. The default tagging efficiencies return 2 (the truth tag
     * is always kept) and the default mistagging rates return -1 (never mistagged).
     */

    class SFSTaggerBase {
    protected:
        /** @brief Flags switching on the detector-level (mis)tagging of each object type. */
        MAbool _isJetTaggingOn, _isTauTaggingEffOn, _isMuonTaggingOn, _isElectronTaggingOn, _isPhotonTaggingOn;
        SFSTaggerBaseOptions _options;

    public:
        /** @brief Constructor. */
        SFSTaggerBase() {}

        /** @brief Destructor. */
        virtual ~SFSTaggerBase() {}

        /** @brief Switch off all detector-level (mis)tagging (overridden by NewTagger). */
        virtual void Initialize()
        {
            /// @brief Booleans for code efficiency
            /// Turn on the usage of tau tagging efficiency
            _isTauTaggingEffOn = false;
            /// Turn on the usage of jet (mis)tagging efficiency
            _isJetTaggingOn = false;
            /// Turn on the usage of muon (mis)tagging efficiency
            _isMuonTaggingOn = false;
            /// Turn on the usage of electron (mis)tagging efficiency
            _isElectronTaggingOn = false;
            /// Turn on the usage of photon (mis)tagging efficiency
            _isPhotonTaggingOn = false;
        }

        /**
         * @brief Apply the truth-level tagging, then the detector-level (mis)tagging, to an event.
         *
         * Mistagged objects are moved to the corresponding collection (e.g. a light jet
         * mistagged as an electron is removed from the jets and added to the electrons),
         * and THT, Meff and MHT are updated accordingly.
         *
         * @param myEvent event (reconstructed objects modified in place).
         */
        void Execute(EventFormat& myEvent) const;

        /**
         * @brief Set the tagging options.
         *
         * @param opt options.
         */
        void SetOptions(SFSTaggerBaseOptions &opt) { _options = opt; }

        /** @brief Print the tagging options. */
        void PrintParam() const;

        /**
         * @brief Accessor to the tagging options.
         *
         * @return a copy of the options.
         */
        SFSTaggerBaseOptions options() const { return _options; }

        /**
         * @brief Truth-level b-tagging: match the jets with the B hadrons (no detector effect).
         *
         * @param myEvent event.
         */
        void BJetTagging(EventFormat& myEvent) const;

        /**
         * @brief Truth-level c-tagging: match the non-b jets with the C hadrons (no detector effect).
         *
         * @param myEvent event.
         */
        void CJetTagging(EventFormat& myEvent) const;

        /**
         * @brief Jet-based hadronic tau tagging: match the light jets with the hadronic taus.
         *
         * @param myEvent event.
         */
        void JetBasedTauTagging(EventFormat& myEvent) const;

        /**
         * @brief Fill a tau object from a jet (momentum, tracks, constituents, decay mode, charge).
         *
         * @param myJet jet.
         * @param myTau tau to fill.
         * @param myEvent event (used to compute the charge from the constituents).
         */
        void Jet2Tau(const RecJetFormat * myJet, RecTauFormat *myTau, EventFormat &myEvent) const;

        ///==========================================//
        ///                                          //
        ///          Tagging Efficiencies            //
        ///                                          //
        ///==========================================//

        /// @brief By default, all efficiencies are initialised as perfect detector

        ///===============//
        ///   B-Tagging   //
        ///===============//

        /**
         * @brief Loose b-tagging efficiency of a true b-jet.
         *
         * @param object b-jet.
         * @return the probability (default 2: always tagged).
         */
        virtual MAfloat32 loose_b_tagging_eff(const RecJetFormat &object) const { return 2.; }

        /**
         * @brief Loose mistagging rate of a true b-jet as a c-jet.
         *
         * @param object b-jet.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 loose_b_mistag_c(const RecJetFormat &object) const { return -1.; }

        /**
         * @brief Medium b-tagging efficiency of a true b-jet.
         *
         * @param object b-jet.
         * @return the probability (default 2: always tagged).
         */
        virtual MAfloat32 mid_b_tagging_eff(const RecJetFormat &object) const { return 2.; }

        /**
         * @brief Medium mistagging rate of a true b-jet as a c-jet.
         *
         * @param object b-jet.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 mid_b_mistag_c(const RecJetFormat &object) const { return -1.; }

        /**
         * @brief Tight b-tagging efficiency of a true b-jet.
         *
         * @param object b-jet.
         * @return the probability (default 2: always tagged).
         */
        virtual MAfloat32 tight_b_tagging_eff(const RecJetFormat &object) const { return 2.; }

        /**
         * @brief Tight mistagging rate of a true b-jet as a c-jet.
         *
         * @param object b-jet.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 tight_b_mistag_c(const RecJetFormat &object) const { return -1.; }

        //===============//
        //   C-Tagging   //
        //===============//

        /**
         * @brief Loose c-tagging efficiency of a true c-jet.
         *
         * @param object c-jet.
         * @return the probability (default 2: always tagged).
         */
        virtual MAfloat32 loose_c_tagging_eff(const RecJetFormat &object) const { return 2.; }

        /**
         * @brief Loose mistagging rate of a true c-jet as a b-jet.
         *
         * @param object c-jet.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 loose_c_mistag_b(const RecJetFormat &object) const { return -1.; }

        /**
         * @brief Medium c-tagging efficiency of a true c-jet.
         *
         * @param object c-jet.
         * @return the probability (default 2: always tagged).
         */
        virtual MAfloat32 mid_c_tagging_eff(const RecJetFormat &object) const { return 2.; }

        /**
         * @brief Medium mistagging rate of a true c-jet as a b-jet.
         *
         * @param object c-jet.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 mid_c_mistag_b(const RecJetFormat &object) const { return -1.; }

        /**
         * @brief Tight c-tagging efficiency of a true c-jet.
         *
         * @param object c-jet.
         * @return the probability (default 2: always tagged).
         */
        virtual MAfloat32 tight_c_tagging_eff(const RecJetFormat &object) const { return 2.; }

        /**
         * @brief Tight mistagging rate of a true c-jet as a b-jet.
         *
         * @param object c-jet.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 tight_c_mistag_b(const RecJetFormat &object) const { return -1.; }

        //=======================//
        //   Light-Jet Tagging   //
        //=======================//

        /**
         * @brief Loose mistagging rate of a light jet as a b-jet.
         *
         * @param object light jet.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 lightjet_mistag_b_loose(const RecJetFormat &object) const { return -1.; }

        /**
         * @brief Loose mistagging rate of a light jet as a c-jet.
         *
         * @param object light jet.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 lightjet_mistag_c_loose(const RecJetFormat &object) const { return -1.; }

        /**
         * @brief Loose mistagging rate of a light jet as a hadronic tau.
         *
         * @param object light jet.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 lightjet_mistag_tau_loose(const RecJetFormat &object) const { return -1.; }

        /**
         * @brief Medium mistagging rate of a light jet as a b-jet.
         *
         * @param object light jet.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 lightjet_mistag_b_mid(const RecJetFormat &object) const { return -1.; }

        /**
         * @brief Medium mistagging rate of a light jet as a c-jet.
         *
         * @param object light jet.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 lightjet_mistag_c_mid(const RecJetFormat &object) const { return -1.; }

        /**
         * @brief Medium mistagging rate of a light jet as a hadronic tau.
         *
         * @param object light jet.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 lightjet_mistag_tau_mid(const RecJetFormat &object) const { return -1.; }

        /**
         * @brief Tight mistagging rate of a light jet as a b-jet.
         *
         * @param object light jet.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 lightjet_mistag_b_tight(const RecJetFormat &object) const { return -1.; }

        /**
         * @brief Tight mistagging rate of a light jet as a c-jet.
         *
         * @param object light jet.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 lightjet_mistag_c_tight(const RecJetFormat &object) const { return -1.; }

        /**
         * @brief Tight mistagging rate of a light jet as a hadronic tau.
         *
         * @param object light jet.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 lightjet_mistag_tau_tight(const RecJetFormat &object) const { return -1.; }

        /**
         * @brief Mistagging rate of a light jet as an electron.
         *
         * @param object light jet.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 lightjet_mistag_electron(const RecJetFormat &object) const { return -1.; }

        /**
         * @brief Mistagging rate of a light jet as a photon.
         *
         * @param object light jet.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 lightjet_mistag_photon(const RecJetFormat &object) const { return -1.; }

        //=================//
        //   Tau Tagging   //
        //=================//

        /**
         * @brief Tau-tagging efficiency of a jet (jet-based tau tagging).
         *
         * @param jet jet, converted into a temporary tau.
         * @param status working point.
         * @return the efficiency of the working point.
         */
        MAfloat32 tau_tagging_eff(const RecJetFormat &jet, TaggerStatus status) const;

        /**
         * @brief Loose tagging efficiency of a hadronic tau.
         *
         * @param object tau.
         * @return the probability (default 2: always tagged).
         */
        virtual MAfloat32 loose_tau_tagging_eff(const RecTauFormat &object) const { return 2.; }

        /**
         * @brief Medium tagging efficiency of a hadronic tau.
         *
         * @param object tau.
         * @return the probability (default 2: always tagged).
         */
        virtual MAfloat32 mid_tau_tagging_eff(const RecTauFormat &object) const { return 2.; }

        /**
         * @brief Tight tagging efficiency of a hadronic tau.
         *
         * @param object tau.
         * @return the probability (default 2: always tagged).
         */
        virtual MAfloat32 tight_tau_tagging_eff(const RecTauFormat &object) const { return 2.; }

        //=======================//
        //   Electron Tagging   //
        //======================//

        /**
         * @brief Mistagging rate of an electron as a muon.
         *
         * @param object electron.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 electron_mistag_muon(const RecLeptonFormat &object) const { return -1.; }

        /**
         * @brief Mistagging rate of an electron as a photon.
         *
         * @param object electron.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 electron_mistag_photon(const RecLeptonFormat &object) const { return -1.; }

        /**
         * @brief Mistagging rate of an electron as a light jet.
         *
         * @param object electron.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 electron_mistag_lightjet(const RecLeptonFormat &object) const { return -1.; }

        //==================//
        //   Muon Tagging   //
        //==================//

        /**
         * @brief Mistagging rate of a muon as an electron.
         *
         * @param object muon.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 muon_mistag_electron(const RecLeptonFormat &object) const { return -1.; }

        /**
         * @brief Mistagging rate of a muon as a photon.
         *
         * @param object muon.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 muon_mistag_photon(const RecLeptonFormat &object) const { return -1.; }

        /**
         * @brief Mistagging rate of a muon as a light jet.
         *
         * @param object muon.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 muon_mistag_lightjet(const RecLeptonFormat &object) const { return -1.; }

        //====================//
        //   Photon Tagging   //
        //====================//

        /**
         * @brief Mistagging rate of a photon as an electron.
         *
         * @param object photon.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 photon_mistag_electron(const RecPhotonFormat &object) const { return -1.; }

        /**
         * @brief Mistagging rate of a photon as a muon.
         *
         * @param object photon.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 photon_mistag_muon(const RecPhotonFormat &object) const { return -1.; }

        /**
         * @brief Mistagging rate of a photon as a light jet.
         *
         * @param object photon.
         * @return the probability (default -1: never mistagged).
         */
        virtual MAfloat32 photon_mistag_lightjet(const RecPhotonFormat &object) const { return -1.; }
    };
}

#endif //MADANALYSIS5_SFSTAGGERBASE_H
